name: Notification Email

on:
  workflow_run:
    workflows:
      - "Merge to Master and Trigger Jenkins Job"
    types:
      - completed
    branches:
      - master

jobs:
  send_notification_email:
    name: Send Notification Email
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Jenkins Job Execution Notification"
          body: "The Jenkins job to containerize and push the application to Docker Hub has been successfully executed."
          to: i200980@nu.edu.pk
