name: Merge to main and Trigger Jenkins Job

on:
  pull_request:
    branches:
      - test

jobs:
  merge_to_main:
    name: Merge to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge changes to main
        run: |
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin main

  trigger_jenkins_job:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    needs: merge_to_main
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v2
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USERNAME }}
          password: ${{ secrets.JENKINS_PASSWORD }}
          job: 'Containerize and Push to Docker Hub'
          parameters: |
            BRANCH=main
